-- CreateTable
CREATE TABLE `Log` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `candidate_id` INTEGER NULL,
    `payload` JSON NOT NULL,
    `response` JSON NOT NULL,
    `new_status` ENUM('NEW', 'PENDING_INTERNAL_REVIEW', 'REJECTED_INTERNAL', 'PENDING_EMPLOYER_REVIEW', 'ACCEPTED_FOR_INTERVIEW', 'REJECTED_FOR_INTERVIEW', 'OFFER_MADE', 'OFFER_DECLINED', 'ACCEPTED_EMPLOYER', 'REJECTED_EMPLOYER', 'CANDIDATE_WITHDREW') NULL,
    `created` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `modified` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Log` ADD CONSTRAINT `Log_candidate_id_fkey` FOREIGN KEY (`candidate_id`) REFERENCES `Candidate`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
